import { LevelData } from '../types/game';

export const CAMPAIGN_LEVELS: LevelData[] = [
  // --- LEVEL 1: Sector 01: Data Nexus Core ---
  {
    id: 1,
    name: 'Sector 01: Data Nexus Core',
    sectorName: 'SECTOR 01',
    description: 'Infiltrate the server complex. Stick to the shadows and eliminate 3 cyber scouts from behind.',
    width: 1000,
    height: 750,
    playerStart: { x: 90, y: 375 },
    parTime: 25,
    coinReward: 250,
    walls: [
      // Outer boundaries
      { x: 30, y: 30, w: 940, h: 20 },
      { x: 30, y: 700, w: 940, h: 20 },
      { x: 30, y: 30, w: 20, h: 690 },
      { x: 950, y: 30, w: 20, h: 690 },

      // Rooms & Corridors
      { x: 220, y: 50, w: 20, h: 250 },
      { x: 220, y: 450, w: 20, h: 250 },

      // Server racks / pillars
      { x: 380, y: 160, w: 60, h: 140, type: 'crate' },
      { x: 380, y: 450, w: 60, h: 140, type: 'crate' },
      { x: 550, y: 260, w: 120, h: 220, type: 'wall' },
      { x: 750, y: 140, w: 50, h: 150, type: 'crate' },
      { x: 750, y: 460, w: 50, h: 150, type: 'crate' },
    ],
    lasers: [],
    terminals: [],
    vents: [
      {
        id: 'vent-1',
        name: 'Maintenance Duct A',
        entrance: { x: 120, y: 120 },
        exit: { x: 320, y: 120 },
        radius: 24,
      },
    ],
    guards: [
      {
        id: 'g1-1',
        type: 'scout',
        x: 340,
        y: 200,
        radius: 18,
        speed: 1.6,
        rotation: 0,
        targetRotation: 0,
        viewDistance: 210,
        fov: (60 * Math.PI) / 180,
        patrolPoints: [
          { x: 340, y: 180 },
          { x: 340, y: 560 },
        ],
        currentPatrolIndex: 0,
        state: 'patrol',
        stateTimer: 0,
      },
      {
        id: 'g1-2',
        type: 'scout',
        x: 680,
        y: 180,
        radius: 18,
        speed: 1.7,
        rotation: Math.PI,
        targetRotation: Math.PI,
        viewDistance: 210,
        fov: (60 * Math.PI) / 180,
        patrolPoints: [
          { x: 680, y: 180 },
          { x: 880, y: 180 },
          { x: 880, y: 360 },
          { x: 680, y: 360 },
        ],
        currentPatrolIndex: 0,
        state: 'patrol',
        stateTimer: 0,
      },
      {
        id: 'g1-3',
        type: 'scout',
        x: 820,
        y: 560,
        radius: 18,
        speed: 1.5,
        rotation: -Math.PI / 2,
        targetRotation: -Math.PI / 2,
        viewDistance: 220,
        fov: (60 * Math.PI) / 180,
        patrolPoints: [
          { x: 820, y: 560 },
          { x: 640, y: 560 },
        ],
        currentPatrolIndex: 0,
        state: 'patrol',
        stateTimer: 0,
      },
    ],
  },

  // --- LEVEL 2: Sector 02: Laser Grid Processing ---
  {
    id: 2,
    name: 'Sector 02: Laser Grid Processing',
    sectorName: 'SECTOR 02',
    description: 'Security lasers block the main corridor. Hack the override console or take the ventilation shaft to bypass the grid.',
    width: 1100,
    height: 800,
    playerStart: { x: 100, y: 400 },
    parTime: 32,
    coinReward: 350,
    walls: [
      // Outer boundaries
      { x: 30, y: 30, w: 1040, h: 20 },
      { x: 30, y: 750, w: 1040, h: 20 },
      { x: 30, y: 30, w: 20, h: 740 },
      { x: 1050, y: 30, w: 20, h: 740 },

      // Main hallway dividers
      { x: 260, y: 50, w: 20, h: 280 },
      { x: 260, y: 470, w: 20, h: 280 },

      // Middle security hub
      { x: 500, y: 180, w: 20, h: 200 },
      { x: 500, y: 450, w: 20, h: 200 },
      { x: 380, y: 370, w: 80, h: 60, type: 'crate' },

      // Back Vault Partition
      { x: 780, y: 50, w: 20, h: 320 },
      { x: 780, y: 480, w: 20, h: 270 },
      { x: 640, y: 120, w: 60, h: 60, type: 'crate' },
      { x: 640, y: 620, w: 60, h: 60, type: 'crate' },
    ],
    lasers: [
      {
        id: 'laser-2-1',
        x1: 280,
        y1: 330,
        x2: 280,
        y2: 470,
        active: true,
        cycleTime: 4.0,
        activeDuration: 2.2,
        timer: 0,
        terminalId: 'term-2-1',
      },
      {
        id: 'laser-2-2',
        x1: 520,
        y1: 380,
        x2: 520,
        y2: 450,
        active: true,
        cycleTime: 3.5,
        activeDuration: 2.0,
        timer: 1.5,
      },
      {
        id: 'laser-2-3',
        x1: 800,
        y1: 370,
        x2: 800,
        y2: 480,
        active: true,
        cycleTime: 5.0,
        activeDuration: 2.8,
        timer: 0,
        terminalId: 'term-2-2',
      },
    ],
    terminals: [
      {
        id: 'term-2-1',
        x: 180,
        y: 160,
        radius: 26,
        targetType: 'laser',
        targetId: 'laser-2-1',
        hacked: false,
        label: 'DISABLE GATE LASER',
      },
      {
        id: 'term-2-2',
        x: 640,
        y: 700,
        radius: 26,
        targetType: 'laser',
        targetId: 'laser-2-3',
        hacked: false,
        label: 'OVERRIDE VAULT LASER',
      },
    ],
    vents: [
      {
        id: 'vent-2-1',
        name: 'Cooling Duct Vent B',
        entrance: { x: 180, y: 650 },
        exit: { x: 640, y: 240 },
        radius: 24,
      },
    ],
    guards: [
      {
        id: 'g2-1',
        type: 'scout',
        x: 380,
        y: 180,
        radius: 18,
        speed: 1.8,
        rotation: 0,
        targetRotation: 0,
        viewDistance: 220,
        fov: (65 * Math.PI) / 180,
        patrolPoints: [
          { x: 380, y: 180 },
          { x: 380, y: 320 },
        ],
        currentPatrolIndex: 0,
        state: 'patrol',
        stateTimer: 0,
      },
      {
        id: 'g2-2',
        type: 'scout',
        x: 640,
        y: 500,
        radius: 18,
        speed: 1.6,
        rotation: Math.PI / 2,
        targetRotation: Math.PI / 2,
        viewDistance: 220,
        fov: (65 * Math.PI) / 180,
        patrolPoints: [
          { x: 640, y: 500 },
          { x: 640, y: 320 },
        ],
        currentPatrolIndex: 0,
        state: 'patrol',
        stateTimer: 0,
      },
      {
        id: 'g2-3',
        type: 'sniper',
        x: 950,
        y: 200,
        radius: 18,
        speed: 0.8,
        rotation: Math.PI,
        targetRotation: Math.PI,
        viewDistance: 380,
        fov: (24 * Math.PI) / 180,
        patrolPoints: [
          { x: 950, y: 200 },
          { x: 950, y: 320 },
        ],
        currentPatrolIndex: 0,
        state: 'patrol',
        stateTimer: 0,
      },
      {
        id: 'g2-4',
        type: 'scout',
        x: 920,
        y: 600,
        radius: 18,
        speed: 1.7,
        rotation: 0,
        targetRotation: 0,
        viewDistance: 220,
        fov: (65 * Math.PI) / 180,
        patrolPoints: [
          { x: 920, y: 600 },
          { x: 840, y: 600 },
        ],
        currentPatrolIndex: 0,
        state: 'patrol',
        stateTimer: 0,
      },
    ],
  },

  // --- LEVEL 3: Sector 03: Cyber-Hound Kennels ---
  {
    id: 3,
    name: 'Sector 03: Cyber-Hound Kennels',
    sectorName: 'SECTOR 03',
    description: 'Recon drones scan in sweeping omni-radars. Deploy smoke grenades and strike before their sweeps ping your location.',
    width: 1150,
    height: 850,
    playerStart: { x: 100, y: 420 },
    parTime: 38,
    coinReward: 450,
    walls: [
      { x: 30, y: 30, w: 1090, h: 20 },
      { x: 30, y: 800, w: 1090, h: 20 },
      { x: 30, y: 30, w: 20, h: 790 },
      { x: 1100, y: 30, w: 20, h: 790 },

      // Central lab obstacles
      { x: 260, y: 160, w: 180, h: 20 },
      { x: 260, y: 650, w: 180, h: 20 },
      { x: 440, y: 160, w: 20, h: 200 },
      { x: 440, y: 470, w: 20, h: 200 },

      // Center tech hub
      { x: 580, y: 320, w: 140, h: 180, type: 'wall' },
      { x: 780, y: 160, w: 20, h: 220 },
      { x: 780, y: 470, w: 20, h: 220 },

      // Crate alcoves
      { x: 300, y: 360, w: 50, h: 100, type: 'crate' },
      { x: 880, y: 240, w: 70, h: 70, type: 'crate' },
      { x: 880, y: 520, w: 70, h: 70, type: 'crate' },
    ],
    lasers: [
      {
        id: 'laser-3-1',
        x1: 460,
        y1: 360,
        x2: 460,
        y2: 470,
        active: true,
        cycleTime: 4.0,
        activeDuration: 2.2,
        timer: 0,
        switchId: 'sw-3-1',
      },
      {
        id: 'laser-3-2',
        x1: 800,
        y1: 380,
        x2: 800,
        y2: 470,
        active: true,
        cycleTime: 4.0,
        activeDuration: 2.0,
        timer: 1.0,
      },
      {
        id: 'laser-3-hall',
        x1: 260,
        y1: 360,
        x2: 260,
        y2: 480,
        active: true,
        cycleTime: 5.0,
        activeDuration: 2.5,
        timer: 0.5,
        switchId: 'sw-3-guard',
      },
    ],
    switches: [
      {
        id: 'sw-3-1',
        x: 480,
        y: 200,
        radius: 24,
        targetLaserId: 'laser-3-1',
        isOn: true,
        label: 'LAB LASER TOGGLE',
        controllableByGuard: false,
      },
      {
        id: 'sw-3-guard',
        x: 340,
        y: 450,
        radius: 24,
        targetLaserId: 'laser-3-hall',
        isOn: true,
        label: 'PATROL SECURITY SWITCH',
        controllableByGuard: true,
      },
    ],
    terminals: [
      {
        id: 'term-3-1',
        x: 650,
        y: 120,
        radius: 26,
        targetType: 'laser',
        targetId: 'laser-3-1',
        hacked: false,
        label: 'DISABLE LAB GRID',
      },
    ],
    vents: [
      {
        id: 'vent-3-1',
        name: 'Service Tunnel Alpha',
        entrance: { x: 140, y: 120 },
        exit: { x: 650, y: 220 },
        radius: 24,
      },
      {
        id: 'vent-3-2',
        name: 'Service Tunnel Beta',
        entrance: { x: 650, y: 620 },
        exit: { x: 1020, y: 720 },
        radius: 24,
      },
    ],
    guards: [
      // Cyber Drone 1
      {
        id: 'g3-d1',
        type: 'drone',
        x: 340,
        y: 240,
        radius: 16,
        speed: 2.4,
        rotation: 0,
        targetRotation: 0,
        viewDistance: 170,
        fov: (90 * Math.PI) / 180,
        patrolPoints: [
          { x: 340, y: 240 },
          { x: 340, y: 600 },
        ],
        currentPatrolIndex: 0,
        state: 'patrol',
        stateTimer: 0,
      },
      // Cyber Drone 2
      {
        id: 'g3-d2',
        type: 'drone',
        x: 940,
        y: 400,
        radius: 16,
        speed: 2.5,
        rotation: Math.PI,
        targetRotation: Math.PI,
        viewDistance: 170,
        fov: (90 * Math.PI) / 180,
        patrolPoints: [
          { x: 940, y: 400 },
          { x: 940, y: 150 },
          { x: 840, y: 150 },
          { x: 840, y: 650 },
          { x: 940, y: 650 },
        ],
        currentPatrolIndex: 0,
        state: 'patrol',
        stateTimer: 0,
      },
      // Sniper
      {
        id: 'g3-s1',
        type: 'sniper',
        x: 650,
        y: 720,
        radius: 18,
        speed: 0.7,
        rotation: -Math.PI / 2,
        targetRotation: -Math.PI / 2,
        viewDistance: 400,
        fov: (22 * Math.PI) / 180,
        patrolPoints: [
          { x: 650, y: 720 },
          { x: 740, y: 720 },
        ],
        currentPatrolIndex: 0,
        state: 'patrol',
        stateTimer: 0,
      },
      // Scouts
      {
        id: 'g3-sc1',
        type: 'scout',
        x: 580,
        y: 180,
        radius: 18,
        speed: 1.8,
        rotation: 0,
        targetRotation: 0,
        viewDistance: 220,
        fov: (60 * Math.PI) / 180,
        patrolPoints: [
          { x: 580, y: 180 },
          { x: 720, y: 180 },
        ],
        currentPatrolIndex: 0,
        state: 'patrol',
        stateTimer: 0,
      },
      {
        id: 'g3-sc2',
        type: 'scout',
        x: 1020,
        y: 350,
        radius: 18,
        speed: 1.7,
        rotation: Math.PI,
        targetRotation: Math.PI,
        viewDistance: 210,
        fov: (60 * Math.PI) / 180,
        patrolPoints: [
          { x: 1020, y: 350 },
          { x: 1020, y: 550 },
        ],
        currentPatrolIndex: 0,
        state: 'patrol',
        stateTimer: 0,
      },
    ],
  },

  // --- LEVEL 4: Sector 04: Vault Citadel ---
  {
    id: 4,
    name: 'Sector 04: Vault Citadel',
    sectorName: 'SECTOR 04',
    description: 'Armored Enforcers carry bulletproof front riot shields. You must assassinate them from behind or freeze them with EMP.',
    width: 1200,
    height: 900,
    playerStart: { x: 100, y: 450 },
    parTime: 45,
    coinReward: 600,
    walls: [
      { x: 30, y: 30, w: 1140, h: 20 },
      { x: 30, y: 850, w: 1140, h: 20 },
      { x: 30, y: 30, w: 20, h: 840 },
      { x: 1150, y: 30, w: 20, h: 840 },

      // Chamber partitions
      { x: 260, y: 50, w: 20, h: 320 },
      { x: 260, y: 530, w: 20, h: 320 },

      // Pillar obstacles
      { x: 420, y: 220, w: 70, h: 70, type: 'crate' },
      { x: 420, y: 610, w: 70, h: 70, type: 'crate' },

      // Central Vault Safe Walls
      { x: 580, y: 150, w: 20, h: 220 },
      { x: 580, y: 530, w: 20, h: 220 },
      { x: 600, y: 150, w: 260, h: 20 },
      { x: 600, y: 730, w: 260, h: 20 },
      { x: 860, y: 150, w: 20, h: 220 },
      { x: 860, y: 530, w: 20, h: 220 },

      // Center vault pillar
      { x: 700, y: 410, w: 80, h: 80, type: 'wall' },

      // Perimeter crates
      { x: 1020, y: 240, w: 60, h: 80, type: 'crate' },
      { x: 1020, y: 580, w: 60, h: 80, type: 'crate' },
    ],
    lasers: [
      {
        id: 'laser-4-1',
        x1: 280,
        y1: 370,
        x2: 280,
        y2: 530,
        active: true,
        cycleTime: 4.5,
        activeDuration: 2.2,
        timer: 0,
        switchId: 'sw-4-corridor',
      },
      {
        id: 'laser-4-moving',
        x1: 520,
        y1: 180,
        x2: 520,
        y2: 360,
        active: true,
        cycleTime: 10.0,
        activeDuration: 10.0,
        timer: 0,
        moving: true,
        moveAxis: 'x',
        moveRange: 280,
        moveSpeed: 1.5,
        initialX1: 520,
        initialY1: 180,
        initialX2: 520,
        initialY2: 360,
      },
      {
        id: 'laser-4-2',
        x1: 880,
        y1: 370,
        x2: 880,
        y2: 530,
        active: true,
        cycleTime: 3.5,
        activeDuration: 1.8,
        timer: 1.0,
        terminalId: 'term-4-vault',
      },
    ],
    switches: [
      {
        id: 'sw-4-corridor',
        x: 220,
        y: 420,
        radius: 24,
        targetLaserId: 'laser-4-1',
        isOn: true,
        label: 'VAULT CORRIDOR LASER CONSOLE',
        controllableByGuard: true,
      },
    ],
    terminals: [
      {
        id: 'term-4-vault',
        x: 720,
        y: 220,
        radius: 26,
        targetType: 'laser',
        targetId: 'laser-4-2',
        hacked: false,
        label: 'DISABLE INNER SANCTUM GATE',
      },
    ],
    vents: [
      {
        id: 'vent-4-1',
        name: 'Underfloor Channel 1',
        entrance: { x: 120, y: 150 },
        exit: { x: 440, y: 150 },
        radius: 24,
      },
      {
        id: 'vent-4-2',
        name: 'Underfloor Channel 2',
        entrance: { x: 440, y: 750 },
        exit: { x: 1050, y: 750 },
        radius: 24,
      },
    ],
    guards: [
      // Enforcer 1 (Armored front)
      {
        id: 'g4-enf1',
        type: 'enforcer',
        x: 460,
        y: 450,
        radius: 20,
        speed: 1.4,
        rotation: 0,
        targetRotation: 0,
        viewDistance: 240,
        fov: (75 * Math.PI) / 180,
        patrolPoints: [
          { x: 460, y: 350 },
          { x: 460, y: 550 },
        ],
        currentPatrolIndex: 0,
        state: 'patrol',
        stateTimer: 0,
        isArmored: true,
      },
      // Enforcer 2
      {
        id: 'g4-enf2',
        type: 'enforcer',
        x: 960,
        y: 450,
        radius: 20,
        speed: 1.3,
        rotation: Math.PI,
        targetRotation: Math.PI,
        viewDistance: 240,
        fov: (75 * Math.PI) / 180,
        patrolPoints: [
          { x: 960, y: 350 },
          { x: 960, y: 550 },
        ],
        currentPatrolIndex: 0,
        state: 'patrol',
        stateTimer: 0,
        isArmored: true,
      },
      // Drone
      {
        id: 'g4-dr',
        type: 'drone',
        x: 720,
        y: 650,
        radius: 16,
        speed: 2.3,
        rotation: 0,
        targetRotation: 0,
        viewDistance: 170,
        fov: (90 * Math.PI) / 180,
        patrolPoints: [
          { x: 620, y: 650 },
          { x: 820, y: 650 },
        ],
        currentPatrolIndex: 0,
        state: 'patrol',
        stateTimer: 0,
      },
      // Snipers
      {
        id: 'g4-sn1',
        type: 'sniper',
        x: 1060,
        y: 120,
        radius: 18,
        speed: 0.6,
        rotation: Math.PI,
        targetRotation: Math.PI,
        viewDistance: 380,
        fov: (22 * Math.PI) / 180,
        patrolPoints: [
          { x: 1060, y: 120 },
          { x: 960, y: 120 },
        ],
        currentPatrolIndex: 0,
        state: 'patrol',
        stateTimer: 0,
      },
      // Scout
      {
        id: 'g4-sc1',
        type: 'scout',
        x: 720,
        y: 350,
        radius: 18,
        speed: 1.6,
        rotation: 0,
        targetRotation: 0,
        viewDistance: 210,
        fov: (60 * Math.PI) / 180,
        patrolPoints: [
          { x: 640, y: 350 },
          { x: 800, y: 350 },
        ],
        currentPatrolIndex: 0,
        state: 'patrol',
        stateTimer: 0,
      },
    ],
  },

  // --- LEVEL 5: Sector 05: The Core - Cyber-Colossus ---
  {
    id: 5,
    name: 'Sector 05: The Core - Cyber-Colossus',
    sectorName: 'SECTOR 05',
    description: 'BOSS ENCOUNTER: Defeat the CYBER-COLOSSUS! Hack the terminals to disable its energy barrier, then strike its exposed rear power core.',
    width: 1250,
    height: 950,
    playerStart: { x: 100, y: 475 },
    parTime: 65,
    coinReward: 1200,
    walls: [
      { x: 30, y: 30, w: 1190, h: 20 },
      { x: 30, y: 900, w: 1190, h: 20 },
      { x: 30, y: 30, w: 20, h: 890 },
      { x: 1200, y: 30, w: 20, h: 890 },

      // Perimeter cover columns
      { x: 260, y: 180, w: 60, h: 140, type: 'wall' },
      { x: 260, y: 630, w: 60, h: 140, type: 'wall' },

      { x: 500, y: 120, w: 100, h: 60, type: 'crate' },
      { x: 500, y: 770, w: 100, h: 60, type: 'crate' },

      { x: 940, y: 180, w: 60, h: 140, type: 'wall' },
      { x: 940, y: 630, w: 60, h: 140, type: 'wall' },

      { x: 740, y: 120, w: 100, h: 60, type: 'crate' },
      { x: 740, y: 770, w: 100, h: 60, type: 'crate' },
    ],
    lasers: [
      {
        id: 'laser-boss-1',
        x1: 420,
        y1: 50,
        x2: 420,
        y2: 240,
        active: true,
        cycleTime: 5.0,
        activeDuration: 2.5,
        timer: 0,
        switchId: 'sw-5-north',
      },
      {
        id: 'laser-boss-2',
        x1: 420,
        y1: 710,
        x2: 420,
        y2: 900,
        active: true,
        cycleTime: 5.0,
        activeDuration: 2.5,
        timer: 2.5,
        switchId: 'sw-5-south',
      },
    ],
    switches: [
      {
        id: 'sw-5-north',
        x: 320,
        y: 180,
        radius: 26,
        targetLaserId: 'laser-boss-1',
        isOn: true,
        label: 'NORTH SECURITY GRID SWITCH',
        controllableByGuard: true,
      },
      {
        id: 'sw-5-south',
        x: 320,
        y: 770,
        radius: 26,
        targetLaserId: 'laser-boss-2',
        isOn: true,
        label: 'SOUTH SECURITY GRID SWITCH',
        controllableByGuard: true,
      },
    ],
    terminals: [
      {
        id: 'term-boss-shield-1',
        x: 380,
        y: 120,
        radius: 28,
        targetType: 'laser',
        targetId: 'boss-shield',
        hacked: false,
        label: 'DISRUPT CORE SHIELD (NORTH)',
      },
      {
        id: 'term-boss-shield-2',
        x: 380,
        y: 830,
        radius: 28,
        targetType: 'laser',
        targetId: 'boss-shield',
        hacked: false,
        label: 'DISRUPT CORE SHIELD (SOUTH)',
      },
    ],
    vents: [
      {
        id: 'vent-boss-1',
        name: 'Coolant Bypass 1',
        entrance: { x: 120, y: 180 },
        exit: { x: 620, y: 120 },
        radius: 24,
      },
      {
        id: 'vent-boss-2',
        name: 'Coolant Bypass 2',
        entrance: { x: 120, y: 770 },
        exit: { x: 620, y: 830 },
        radius: 24,
      },
      {
        id: 'vent-boss-3',
        name: 'Rear Flank Vent',
        entrance: { x: 840, y: 120 },
        exit: { x: 1100, y: 475 },
        radius: 24,
      },
    ],
    guards: [
      {
        id: 'boss-minion-1',
        type: 'drone',
        x: 480,
        y: 320,
        radius: 16,
        speed: 2.1,
        rotation: 0,
        targetRotation: 0,
        viewDistance: 170,
        fov: (90 * Math.PI) / 180,
        patrolPoints: [
          { x: 480, y: 320 },
          { x: 480, y: 630 },
        ],
        currentPatrolIndex: 0,
        state: 'patrol',
        stateTimer: 0,
      },
      {
        id: 'boss-minion-2',
        type: 'scout',
        x: 880,
        y: 350,
        radius: 18,
        speed: 1.8,
        rotation: Math.PI,
        targetRotation: Math.PI,
        viewDistance: 210,
        fov: (60 * Math.PI) / 180,
        patrolPoints: [
          { x: 880, y: 350 },
          { x: 880, y: 600 },
        ],
        currentPatrolIndex: 0,
        state: 'patrol',
        stateTimer: 0,
      },
    ],
    boss: {
      id: 'boss-colossus',
      type: 'boss',
      x: 720,
      y: 475,
      radius: 38,
      speed: 1.1,
      rotation: Math.PI,
      targetRotation: Math.PI,
      viewDistance: 320,
      fov: (100 * Math.PI) / 180,
      patrolPoints: [
        { x: 720, y: 360 },
        { x: 820, y: 475 },
        { x: 720, y: 590 },
        { x: 620, y: 475 },
      ],
      currentPatrolIndex: 0,
      state: 'patrol',
      stateTimer: 0,
      maxHealth: 5,
      health: 5,
      phase: 1,
      shieldActive: true,
      attackCooldown: 3.5,
      attackPattern: 'sweep',
      warningAreas: [],
    },
  },
];
