import { SkinItem, BladeTrailItem, PerkUpgrade } from '../types/game';

export const SKINS: SkinItem[] = [
  {
    id: 'default',
    name: 'Neon Shadow',
    cost: 0,
    color: '#00f0ff',
    accentColor: '#0ea5e9',
    description: 'Standard issue cyber assassin operative suit.',
    speedBonus: 0,
    reachBonus: 0,
    perkText: 'Balanced tactical stats',
  },
  {
    id: 'ninja',
    name: 'Cyber Ninja',
    cost: 450,
    color: '#ff0055',
    accentColor: '#f43f5e',
    description: 'Lightweight titanium cybernetics for lightning sprints.',
    speedBonus: 0.18,
    reachBonus: 0,
    perkText: '+18% Movement Speed',
  },
  {
    id: 'ghost',
    name: 'Phantom Ghost',
    cost: 750,
    color: '#a855f7',
    accentColor: '#c084fc',
    description: 'Reflective optical mesh that delays guard reaction time.',
    speedBonus: 0.05,
    reachBonus: 0,
    perkText: '+0.4s Guard Reaction Delay',
  },
  {
    id: 'vanguard',
    name: 'Crimson Vanguard',
    cost: 1100,
    color: '#ef4444',
    accentColor: '#b91c1c',
    description: 'Reinforced cyber-exoskeleton with extended hydraulic blade arm.',
    speedBonus: 0.05,
    reachBonus: 0.3,
    perkText: '+30% Melee Strike Range',
  },
  {
    id: 'gold',
    name: 'Gold Sovereign',
    cost: 1800,
    color: '#eab308',
    accentColor: '#facc15',
    description: 'Opulent gilded nanotech that siphons maximum cyber credits.',
    speedBonus: 0.12,
    reachBonus: 0.15,
    perkText: '+50% Bonus Credits on Kills',
  },
];

export const BLADE_TRAILS: BladeTrailItem[] = [
  {
    id: 'cyan',
    name: 'Cyan Edge',
    cost: 0,
    color: '#00f0ff',
    particleColor: '#38bdf8',
    description: 'Clean high-frequency plasma blade emission.',
  },
  {
    id: 'sakura',
    name: 'Sakura Spark',
    cost: 300,
    color: '#ec4899',
    particleColor: '#f472b6',
    description: 'Vibrant neon cherry blossom energy discharge.',
  },
  {
    id: 'plasma_gold',
    name: 'Gold Plasma',
    cost: 600,
    color: '#eab308',
    particleColor: '#fde047',
    description: 'Supercharged ionized golden electricity.',
  },
  {
    id: 'void',
    name: 'Void Rift',
    cost: 900,
    color: '#8b5cf6',
    particleColor: '#a78bfa',
    description: 'Dark matter singularity trail that absorbs light.',
  },
];

export const PERK_UPGRADES: PerkUpgrade[] = [
  {
    id: 'speedLevel',
    name: 'Hyper Servos',
    level: 1,
    maxLevel: 4,
    baseCost: 250,
    description: 'Enhances leg actuators for faster stalking movement.',
    statBonus: '+10% Movement Speed per tier',
  },
  {
    id: 'reachLevel',
    name: 'Vibro-Extension',
    level: 1,
    maxLevel: 4,
    baseCost: 250,
    description: 'Lengthens plasma blade edge for longer assassination strikes.',
    statBonus: '+12% Melee Strike Range per tier',
  },
  {
    id: 'stealthLevel',
    name: 'Refraction Mesh',
    level: 1,
    maxLevel: 3,
    baseCost: 350,
    description: 'Grants extra reaction time before guards raise sirens.',
    statBonus: '+0.2s Detection Grace per tier',
  },
  {
    id: 'gadgetLevel',
    name: 'Nanite Fabricator',
    level: 1,
    maxLevel: 3,
    baseCost: 400,
    description: 'Allows carrying additional gadget charges into each sector.',
    statBonus: '+1 Max Charge for All Gadgets per tier',
  },
];
